# Generated by Django 3.2.4 on 2021-06-19 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameoftable', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_title', models.CharField(max_length=200)),
                ('display_text', models.CharField(max_length=200)),
                ('display_link', models.CharField(max_length=200)),
                ('display_photo', models.CharField(max_length=200)),
                ('feed_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.feedtable')),
            ],
        ),
    ]
