# Generated by Django 3.2.4 on 2021-06-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='content_blog',
            field=models.CharField(default='None', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feed',
            name='display_title',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
