# Generated by Django 3.2.4 on 2021-06-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_alter_feed_display_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='display_photo',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
