# Generated by Django 3.2.4 on 2021-06-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_alter_feed_display_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='display_photo',
            field=models.ImageField(upload_to='feed/static/feed/<django.db.models.query_utils.DeferredAttribute object at 0x000001E42BBCBCD0>/'),
        ),
    ]
