# Generated by Django 3.2.4 on 2021-06-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_auto_20210622_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='store_photo_at',
        ),
        migrations.AlterField(
            model_name='feed',
            name='display_photo',
            field=models.ImageField(null=True, upload_to='static/feed/'),
        ),
    ]
