# Generated by Django 3.2.4 on 2021-06-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_alter_feed_display_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedtable',
            name='descrip',
            field=models.CharField(default='None', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feed',
            name='display_photo',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
